### ISSUE TITLE
Activate HTTPS 

### ISSUE THREAD

**Issue by shreaker** [shreaker/Secure_Software_Demo#15]
Block http connection
Get a certificate e.g.: https://letsencrypt.org/

**Comment by shreaker** [comment]
See: https://salty-anchorage-26470.herokuapp.com 
Contact @faryon93

**Comment by faryon93** [comment]
Heroku already provides ssl termination with a ssl certificate of there own. So a redirect from http -> https just needs to be implemented?

**Comment by shreaker** [comment]
@frozen-void

**Comment by faryon93** [comment]
Forcing of a secure ssl connection is only supported on heroku, so that local development is possible without ssl.
