### ISSUE TITLE
xss vulnerability in (every) form

### ISSUE THREAD

**Issue by faryon93** [shreaker/Secure_Software_Demo#23]
When placing transactions no stripping or quoting is done. So it is possible to send javascript code as "verwendungszweck" which is executed when the target user of a transaction opens the "view transactions" page.

**Comment by faryon93** [comment]
Just commited a version with xss filtering. Please test, i'm not 100% sure if i considered all eventualities.

**Comment by shreaker** [comment]
fixed and tested.
