### ISSUE TITLE
Deployment on Heroku

### ISSUE THREAD

**Issue by faryon93** [shreaker/Secure_Software_Demo#8]
Using a free Heroku dyno to deploy the application. The instance is configured in development mode, which means the database is resetted on every redeploy or cycling of the dyno (every 24h).

https://salty-anchorage-26470.herokuapp.com

TODO:
- proper persistent database (pgsql)
- integrate heroku config to public repository

**Comment by shreaker** [comment]
How often is the app deployed. A bit faster would be nice :-)

**Comment by faryon93** [comment]
Whenever I hit the deploy button ;) maybe there is a way to deploy automatically on every push to github.

**Comment by faryon93** [comment]
Our directory structure is not suitable for automatic deployments to heroku

**Comment by shreaker** [comment]
My Heroku account: shreaker.figa@gmx.net

**Comment by faryon93** [comment]
Added you as collaborator. Hope this is sufficient for deployments.

- install heroku-toolbelt
- add git remote using heroku-toolbelt
- deploy using "make" in the root directory

**Comment by faryon93** [comment]
Using persistent pqsql database on heroku. For developement a temporary h2 database is used.
